import mongoose from 'mongoose'

const commentSchema = new mongoose.Schema(
  {
    // which session this comment belongs to — indexed for fast lookup
    sessionId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'CodeSession',
      required: true,
      index: true,
    },

    // the editor line number where the comment is anchored (1-based)
    lineNumber: {
      type: Number,
      required: true,
      min: 1,
    },

    text: {
      type: String,
      required: true,
      trim: true,
      maxlength: 2000,
    },

    // the user who posted this comment
    author: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      required: true,
    },

    // true when this comment was generated by the AI review feature (Day 4)
    isAiGenerated: {
      type: Boolean,
      default: false,
    },
  },
  {
    timestamps: true,
  }
)

export default mongoose.model('Comment', commentSchema)
